### ISSUE TITLE
Remaining issues for 2.1

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#873]
listing the important stuff still to do or to think about.
minor issues not listed here, as they might skip over to 2.2

stuff to add / implement new:
- [x] simple audio gain plugin #683
- [x] clear logs button #839
- [x] midi2cv plugin (mono)
- [x] nsm warning if project not saved yet

undecided:
- [x] exposing parameters to carla-vst #424 
- [x] drag&drop into patchbay #759 (done in 2.2)

remaining stuff to fix:
- [x] fix remaining patchbay changes and behaviour (needs another meta-ticket) #836 #824 
- [ ] fix plugin version not loading all values sometimes #831
- [ ] finalize internal jack client #862 
- [x] <s>make inline display stable</s> (won't do)
- [x] bridge issues #545 
- [ ] figure out a way to keep handling events when carla-plugin ui is hidden #825
